name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout source code
        uses: actions/checkout@v2

      - name: â˜• Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: ğŸš€ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"

      - name: ğŸ“¥ Install dependencies
        run: flutter pub get

      - name: ğŸ› ï¸ Build APK (Release)
        run: flutter build apk --release

      - name: ğŸ› ï¸ Build AppBundle (Release)
        run: flutter build appbundle --release

      - name: ğŸ“¤ Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: ğŸ“¤ Upload AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

      - name: ğŸ Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: ğŸ“¦ Install Python Dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests speedtest-cli pyyaml

      - name: â˜ï¸ Upload Artifacts to Google Drive and Send Telegram Message
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: "nassimsolimanflutter@gmail.com"

        run: python upload_to_gdrive.py
